### ISSUE TITLE
Improve the word-wrapping/word-breaking support

### ISSUE THREAD

**Issue by fref** [ralfstuckert/pdfbox-layout#10]
As of now, word-wrapping happens at word boundaries. (through TextSequenceUtil.drawText -> wordWrapToLines -> wordWrapToLines)
This can be annoying for small columns where a single big word needs to be inserted or if _Justify_ is supported as alignment someday.

It would be nice to be able to 
- force a line break inside the word if there is not enough place to put the word on the line (and there is no "white space" available for pdfbox-layout to break automatically) ("hard cut")
- provide a "strategy" when drawing a TextFlow that would hint to pdfbox-layout where clean "soft cuts" can be inserted into a word (see https://en.wikipedia.org/wiki/Hyphenation_algorithm)
- make pdfbox-layout write an hyphen when a soft/hard cut happened (maybe a configurable character for hard cut)

**Comment by ralfstuckert** [comment]
Added word breaking as a strategy for 0.8.5, but I still have to write some doc on this topic

**Comment by ralfstuckert** [comment]
See wiki page on word break

**Comment by fref** [comment]
Brilliant!
