### ISSUE TITLE
Wrap text when longer then width of the page

### ISSUE THREAD

**Issue by kwladyka** [ralfstuckert/pdfbox-layout#12]
Like in CSS when have text like:
`foo-bar-fooooooooo-bbbaaaaaaaarrrrrr`

and page width is
`--------------------------`

It will break text in `-` points to get:
```
foo-bar-fooooooooo-
bbbaaaaaaaarrrrrr
```

Are we able to do the same thing here?

**Comment by ralfstuckert** [comment]
I'm working on this for #10

**Comment by ralfstuckert** [comment]
Works in version 0.8.5, but I still have to write some doc on that.

**Comment by kwladyka** [comment]
Hi,

I have long break in all my reported issues. I apologise. I will back to this topics in 1-2 months. I had to change the priority in project after "good enough" (what mean poor quality). But i will back to this topic for sure, because i have to.
