### ISSUE TITLE
HTML support

### ISSUE THREAD

**Issue by amrfaissal** [ralfstuckert/pdfbox-layout#13]
Hi @ralfstuckert. Any pointers on how to use `pdfbox-layout` with HTML markup? Thanks.

**Comment by ralfstuckert** [comment]
What exactly is your intention resp. your expectations?

**Comment by amrfaissal** [comment]
Ability to parse HTML/CSS input and render it inside the PDF. After some digging, this can be achieved using JSOUP. If you're interested, I'll raise a PR with this feature.

**Comment by ralfstuckert** [comment]
This project is intended to provide some thin layer on top of PDFBox to ease creation of simple documents. Converting HTML to PDF is out of scope.
Sorry :-\
