### ISSUE TITLE
Underline Text

### ISSUE THREAD

**Issue by atown45** [ralfstuckert/pdfbox-layout#14]
Hello,

I just started using the latest version of pdfbox-layout and really like the functionality it provides.  It has made my PDF generation efforts much easier.  I have a question, tho.   How do I underline text?  

For example:
   Paragraph paragraph = new Paragraph();
   paragraph.addText("NAME", 12, BaseFont.Times.getPlainFont());  **// NAME needs to be underlined**
   document.add(paragraph, VerticalLayoutHint.RIGHT);

Thanks for any insight.

**Comment by ralfstuckert** [comment]
Currently you can't, except for hyperlinks. Alas, this is not as trivial as one might think. I will have a look at it the next days.

**Comment by ralfstuckert** [comment]
I guess underlining will be part of one of the next releases. In the mean time you may have a look at #16, which describes how I will implement that after all.

**Comment by atown45** [comment]
Thank you for the quick turnaround.  What you discussed in #16 looks good.  I'll try implementing it in my app. 

Thanks again!

**Comment by ralfstuckert** [comment]
Just to save you some time: I guess I will make the next release - including underline - this week.

**Comment by ralfstuckert** [comment]
And with markup support for underline, of course.

**Comment by ralfstuckert** [comment]
Fixed in 0.9.0, Markup is double underscore

**Comment by atown45** [comment]
WOW!!!  Talk about service.  :-)

Thank you so much for this.  Your tool rocks!!!!
