### ISSUE TITLE
Support of additional level 'Flow'

### ISSUE THREAD

**Issue by Parz90** [ralfstuckert/pdfbox-layout#15]
I saw that pdfbox-layout has frames in a document and paragraphs in a frame. I need one more level between document and frame that can be places to specific positions. 

- Document has flows
- Flow has frames
- Frame has paragraphs

Flows have for example Parameters like: xCoord, yCoord, width and height.

How can I do this? Is there already existing something similar?

**Comment by ralfstuckert** [comment]
I guess you want some kind of nested layouts, is that correct?

**Comment by Parz90** [comment]
Hi ralfstuckert,

Yes, exactly. I have for example 1 page with several flows that I can set the position. And the flows have paragraphs inside. 

One more question is, how to manually to a page break? 

Thank you for your help.

**Comment by ralfstuckert** [comment]
Sorry, nested layout is not possible with the current design, since layouting is done on the fly during rendering. To allow arbitrary nesting, a pre-rendering layout phase would be needed.

**Comment by bdeterling** [comment]
Does this mean that it's not possible to have multiple elements within a frame? For example, I would like to have multiple images in a frame or an image and some text. Basically, I just want to draw a box around multiple elements.
