### ISSUE TITLE
Hyperlink position wrong in landscape 

### ISSUE THREAD

**Issue by ralfstuckert** [ralfstuckert/pdfbox-layout#17]
In landscape (rotated) mode the positions of the hyperlink annotations are wrong.

**Comment by ralfstuckert** [comment]
Fixed in 0.9.0

**Comment by mfkrohn** [comment]
The links are positioned correctly in landscape now, but if I have an anchor that is also a link, that anchor will go to the wrong location. It seems the anchor x and y position values are flipped. If the anchor is positioned with a smaller x value, the link will jump to the top of the page its on. With larger x values the return link will jump to the page below the anchor location.
