### ISSUE TITLE
Overline, linethrough and superscript text

### ISSUE THREAD

**Issue by Parz90** [ralfstuckert/pdfbox-layout#20]
I would like to underline, overline, linethrough and superscript text. 

I there any possibility to do this?

Thank you.

**Comment by ralfstuckert** [comment]
Underline is already supported. 
Strike (and maybe overline) is something you can achieve using custom annotations, have a look to the wiki on that.

I have never dealt with sub- or superscript yet. How would you do that manually?

**Comment by Parz90** [comment]
Ok, I will try to implement Strike and overline soon with custom annotations. I let you know as soon as I have tried.

superscript, I know a software where I can set a boolean to true(button) and the paragraph is after a superscript. But I really not sure how we can implement this. But it will be nice to have something similar.

<img width="268" alt="screen shot 2017-03-08 at 18 20 44" src="https://cloud.githubusercontent.com/assets/20877378/23715218/2ea42ea4-042c-11e7-8d7e-3110796513dc.png">

**Comment by ralfstuckert** [comment]
Fixed in 1.0.0. See https://github.com/ralfstuckert/pdfbox-layout/wiki/Markup
