### ISSUE TITLE
Maven central

### ISSUE THREAD

**Issue by andytrofimov** [ralfstuckert/pdfbox-layout#23]
Could you deploy your artifact to Maven central please. 
It would be much more easier to use it, because u don't need to add additional repositories to your project.
Thank you.

**Comment by ralfstuckert** [comment]
Sorry, I won't do that. Deploying to maven central is a pain, that's why so many people are using JitPack by now.

**Comment by helpermethod** [comment]
Hi @ralfstuckert!

Nowadays JReleaser eases some of the pain related to Maven Central publication. If you would accepts some PRs, I'll gladly help out.
