### ISSUE TITLE
Aligment justified

### ISSUE THREAD

**Issue by victommasi** [ralfstuckert/pdfbox-layout#25]
Is there any way to set paragraph aligment justified? I only see these choices: center, left, right.

**Comment by ralfstuckert** [comment]
Currently not, since I did not need that so far. But give some days to give it a try.

**Comment by ralfstuckert** [comment]
Would you expect justification to be done by word- or character-spacing?

**Comment by victommasi** [comment]
I expect justification to be done by word, like is done by itext library.

**Comment by ralfstuckert** [comment]
Fixed in 1.0.0
