### ISSUE TITLE
please deploy to maven central

### ISSUE THREAD

**Issue by jjYBdx4IL** [ralfstuckert/pdfbox-layout#38]
I don't like to use artifacts from repositories owned by private companies. Those can vanish every day. Also, I heard rumors that deployment to central is really easy from your current public maven host.

**Comment by ralfstuckert** [comment]
Duplicate of #23, see my explanation there. I do not know a really easy way of deploying to maven central. I have done it, and I do not like it. If you have any hints on easing that up, I would be glad to do so.
