### ISSUE TITLE
Can pdfbox-layout set text to invisible?

### ISSUE THREAD

**Issue by arnthom** [ralfstuckert/pdfbox-layout#57]
I found that pdfbox can set a rendering mode (RENDERING_MODE_NEITHER_FILL_NOR_STROKE_TEXT) for text, so that this is invisible (foregroundcolor is backgroundcolor).
Is the a markup for pdfbox-layout to do such thing?

**Comment by ralfstuckert** [comment]
Not that way. But you can set the color by using markup, see the [wiki](https://github.com/ralfstuckert/pdfbox-layout/wiki/Markup).

**Comment by arnthom** [comment]
ok, this was just an alternativ route to indentation, but meanwhile a different approach works well.
