### ISSUE TITLE
line height

### ISSUE THREAD

**Issue by kwladyka** [ralfstuckert/pdfbox-layout#6]
Is it possible to set line height for wrapping? or just +x to every line?

**Comment by ralfstuckert** [comment]
You can set the line spacing on a TextFlow/Paragraph, which is a factor applied to the line height.

Does that fit your needs?

**Comment by ralfstuckert** [comment]
Please let me know, if this fulfills your needs, so I may close the issue.

**Comment by ralfstuckert** [comment]
No feedback in half a year, so will close this issue. Sorry.

**Comment by kwladyka** [comment]
So sorry... i still use your work and it is great. Unfortunately all the time something else have higher priority, but i will back to improve it one day... really want to.
