### ISSUE TITLE
jump to position Y

### ISSUE THREAD

**Issue by kwladyka** [ralfstuckert/pdfbox-layout#7]
I am writing text in PDF and no matter what is the height i have to jump to specific Y position and continue.

So:
```
foo
bar
#jump to Y position and continue, just want start this part of the PDF always from that place whatever i wrote before
baz
```

How can i do that?

**Comment by ralfstuckert** [comment]
This feature already exists, see rst.pdfbox.layout.elements.PositionControl.createSetPosition(Float, Float)

**Comment by kwladyka** [comment]
Sorry, but i have to miss something... How exactly use it? On Document? How?

I created position
```clojure
(PositionControl/createSetPosition 0 (mm->points 10))
```

But how to use it? On the Document class? Or Paragraph?

**Comment by ralfstuckert** [comment]
This is an Element like e.g. Paragraph, so you add it to the document.

**Comment by kwladyka** [comment]
Oh it works in not obviously way. The Y dimension mean the distance from the bottom, not from the top. Is it a bug or it should be like that? I can still use it i think in my case.

**Comment by ralfstuckert** [comment]
Yep, all positions are in the PDF coordinate space, where the origin is the lower left corner.
