### ISSUE TITLE
pdfbox2-layout missing in jitpack.io

### ISSUE THREAD

**Issue by benridge** [ralfstuckert/pdfbox-layout#88]
The jar is not in the jitpack location any more. This occurred sometime in the last 3 days.
Previously working URL is
https://jitpack.io/com/github/ralfstuckert/pdfbox-layout/pdfbox2-layout/1.0.0/pdfbox2-layout-1.0.0.jar
build.log shows that it built back in 2017 and published the jar there
https://jitpack.io/com/github/ralfstuckert/pdfbox-layout/pdfbox2-layout/1.0.0/build.log

**Comment by cdietze** [comment]
This artefact can also be found on the mulesoft repository (https://repository.mulesoft.org/nexus/content/repositories/public/).
I found this via: https://mvnrepository.com/artifact/com.github.ralfstuckert.pdfbox-layout/pdfbox2-layout/1.0.0

**Comment by grasshopper7** [comment]
@cdietze Thanks for this information.

**Comment by ralfstuckert** [comment]
Sorry, this library is no longer under development as it proved to be a dead end. Anyway if you like to use it, I provided a version 1.0.1 that fixed the problems that arised with java 8 (javadoc).
